/**
 * Restaurantica restaurant recommendation system
 * ECSE 321 - Introduction to Software Engineering
 * Term-Long Project, Misson 4, Due: 03, Dec, 2009
 *==============================================================================
 * Rating entity class - stores rating objects for use in the system.
 *==============================================================================
 * A simple class, just constructors, getters, and setters. The most important
 * thing to know about this entity class is that it does NOT verify the contents
 * of the rating you use. It is up to the caller to ensure that the information
 * stored is all valid!
 *==============================================================================
 * Author: Iain Macdonald - Nov./Dec. 2009
 * For questions, or comments e-mail:
 * xiainx@gmail.com
 */

package entities;

import java.util.Date;

public class Rating extends entity {

    // Fields from the database
    private int ratingID;
    private int userID;
    private int restaurantID;
    private int rating;
    private String comment;
    private Date ratingDate;
    private boolean flagged;

    /**
     * Parameterless constructor
     * 
     * Does not initialize any fields in the object. This constructor should be
     * used higher up, for creating new ratings for the database.
     */
    public Rating() {}

    /**
     * Parameterized constructor
     *
     * Initialize all fields to the input values. When using, please pay
     * attention to the order of the arguments. If you do not know a particular
     * argument, and would still like to use this constructor, enter -1, "", or
     * null for that the unknown fields. This constructor should be used for
     * database retrieval operations, to easily initialize all fields for the
     * particular rating.
     */
    public Rating(int ratingID, int userID, int restaurantID, int rating, String comment, Date
		  ratingDate, boolean flagged) {
	this.ratingID = ratingID;
	this.userID = userID;
	this.restaurantID = restaurantID;
	this.rating = rating;
	this.comment = comment;
	this.ratingDate = ratingDate;
	this.flagged = flagged;
    }

    // Getters & Setters - Automatically generated by NetBeans
    public String getComment() {
	return comment;
    }

    public void setComment(String comment) {
	this.comment = comment;
    }

    public boolean getFlagged() {
	return flagged;
    }

    public void setFlagged(boolean flagged) {
	this.flagged = flagged;
    }

    public int getRating() {
	return rating;
    }

    public void setRating(int rating) {
	this.rating = rating;
    }

    public Date getRatingDate() {
	return ratingDate;
    }

    public void setRatingDate(Date ratingDate) {
	this.ratingDate = ratingDate;
    }

    public int getRatingID() {
	return ratingID;
    }

    public void setRatingID(int ratingID) {
	this.ratingID = ratingID;
    }

    public int getRestaurantID() {
	return restaurantID;
    }

    public void setRestaurantID(int restaurantID) {
	this.restaurantID = restaurantID;
    }

    public int getUserID() {
	return userID;
    }

    public void setUserID(int userID) {
	this.userID = userID;
    }

    /**
     * toString
     *
     * Returns the current state of the rating object as a string.
     */
    public String toString(){

	String returnString = "";
	String nxt = ", ";

	// concatenate all fields to the return string
	returnString += ratingID + nxt;
	returnString += userID + nxt;
	returnString += restaurantID + nxt;
	returnString += rating + nxt;
	returnString += comment + nxt;
	returnString += ratingDate + nxt;
	returnString += flagged;

	return returnString;
	
    }

}