/**
 * Restaurantica restaurant recommendation system
 * ECSE 321 - Introduction to Software Engineering
 * Term-Long Project, Misson 4, Due: 03, Dec, 2009
 *==============================================================================
 * Restaurant entity class - stores restaurant objects for use in the system.
 *==============================================================================
 * A simple class, just constructors, getters, and setters. The most important
 * thing to know about this entity class is that it does NOT verify the contents
 * of the restaurant you use. It is up to the caller to ensure that the
 * information stored is all valid!
 *==============================================================================
 * Author: Iain Macdonald - Nov. 2009
 * For questions, or comments e-mail:
 * xiainx@gmail.com
 */

package entities;

public class Restaurant extends entity {

    // Fields from the database
    private int restaurantID;
    private float averageRating;
    private int numberOfRatings;
    private String name;
    private int streetNumber;
    private String streetName;
    private String postalCode;
    private String city;
    private String province;
    private String country;
    private String phone;
    private String cuisine;
    private String webaddress;
    private String openHours;
    private String closeHours;
    private float cost;
    private boolean alcohol;
    private String payment;
    private String description;
    private boolean reservationsAccepted;
    private boolean reservationsRecommended;
    private String imagePath;

    /**
     * Parameterless Constructor
     *
     * Does not initialize any fields in the object. This constructor should be
     * used higher up, for creating new restaurants for the database.
     */
    public Restaurant() {}

    /**
     * Parameterized constructor
     *
     * Initializes all fields to the input values. When using, please pay
     * attention to the order of arguments. If you do not know a particular
     * argument, and would still like to use this constructor, enter -1, "", or
     * null for the unknown fields. This constructor should generally be used
     * lower down, for moving objects from the database.
     *
     * @param restaurantID
     * @param averageRating
     * @param numberOfRatings
     * @param name
     * @param streetNumber
     * @param streetName
     * @param postalCode
     * @param city
     * @param province
     * @param country
     * @param phone
     * @param cuisine
     * @param webaddress
     * @param openHours
     * @param closeHours
     * @param cost
     * @param alcohol
     * @param payment
     * @param description
     * @param reservationsAccepted
     * @param reservationsRecommended
     * @param imagePath
     */
    public Restaurant(int restaurantID, float averageRating, 
	    int numberOfRatings, String name, int streetNumber,
	    String streetName, String postalCode, String city, String province,
	    String country, String phone, String cuisine, String webaddress,
	    String openHours, String closeHours, float cost, boolean alcohol,
	    String payment, String description, boolean reservationsAccepted,
	    boolean reservationsRecommended, String imagePath) {
	this.restaurantID = restaurantID;
	this.averageRating = averageRating;
	this.numberOfRatings = numberOfRatings;
	this.name = name;
	this.streetNumber = streetNumber;
	this.streetName = streetName;
	this.postalCode = postalCode;
	this.city = city;
	this.province = province;
	this.country = country;
	this.phone = phone;
	this.cuisine = cuisine;
	this.webaddress = webaddress;
	this.openHours = openHours;
	this.closeHours = closeHours;
	this.cost = cost;
	this.alcohol = alcohol;
	this.payment = payment;
	this.description = description;
	this.reservationsAccepted = reservationsAccepted;
	this.reservationsRecommended = reservationsRecommended;
	this.imagePath = imagePath;
    }

    // Getters & Setters, automatically generated by NetBeans
    public boolean getAlcohol() {
	return alcohol;
    }

    public void setAlcohol(boolean alcohol) {
	this.alcohol = alcohol;
    }

    public String getDescription() {
	return description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    public float getAverageRating() {
	return averageRating;
    }

    public void setAverageRating(float averageRating) {
	this.averageRating = averageRating;
    }

    public String getCity() {
	return city;
    }

    public void setCity(String city) {
	this.city = city;
    }

    public String getCloseHours(){
	return this.closeHours;
    }

    public void setCloseHours(String closeHours) {
	this.closeHours = closeHours;
    }

    public float getCost() {
	return cost;
    }

    public void setCost(float cost) {
	this.cost = cost;
    }

    public String getCountry() {
	return country;
    }

    public void setCountry(String country) {
	this.country = country;
    }

    public String getCuisine() {
	return cuisine;
    }

    public void setCuisine(String cuisine) {
	this.cuisine = cuisine;
    }

    public String getImagePath() {
	return imagePath;
    }

    public void setImagePath(String imagePath) {
	this.imagePath = imagePath;
    }

    public String getName() {
	return name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public int getNumberOfRatings() {
	return numberOfRatings;
    }

    public void setNumberOfRatings(int numberOfRatings) {
	this.numberOfRatings = numberOfRatings;
    }

    public String getOpenHours() {
	return openHours;
    }

    public void setOpenHours(String openHours) {
	this.openHours = openHours;
    }

    public String getPayment() {
	return payment;
    }

    public void setPayment(String payment) {
	this.payment = payment;
    }

    public String getPhone() {
	return phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    public String getPostalCode() {
	return postalCode;
    }

    public void setPostalCode(String postalCode) {
	this.postalCode = postalCode;
    }

    public String getProvince() {
	return province;
    }

    public void setProvince(String province) {
	this.province = province;
    }

    public boolean getReservationsAccepted() {
	return reservationsAccepted;
    }

    public void setReservationsAccepted(boolean reservationsAccepted) {
	this.reservationsAccepted = reservationsAccepted;
    }

    public boolean getReservationsRecommended() {
	return reservationsRecommended;
    }

    public void setReservationsRecommended(boolean reservationsRecommended) {
	this.reservationsRecommended = reservationsRecommended;
    }

    public int getRestaurantID() {
	return restaurantID;
    }

    public void setRestaurantID(int restaurantID) {
	this.restaurantID = restaurantID;
    }

    public String getStreetName() {
	return streetName;
    }

    public void setStreetName(String streetName) {
	this.streetName = streetName;
    }

    public int getStreetNumber() {
	return streetNumber;
    }

    public void setStreetNumber(int streetNumber) {
	this.streetNumber = streetNumber;
    }

    public String getWebaddress() {
	return webaddress;
    }

    public void setWebaddress(String webaddress) {
	this.webaddress = webaddress;
    }

    /**
     * toString
     *
     * returns the current state of the object in a string.
     */
    public String toString(){

	String returnString = "";
	String nxt = ", ";

	// Concatenate all fields to the returnString
	returnString += restaurantID + nxt;
	returnString += averageRating + nxt;
	returnString += numberOfRatings + nxt;
	returnString += name + nxt;
	returnString += streetNumber + nxt;
	returnString += streetName + nxt;
	returnString += postalCode + nxt;
	returnString += city + nxt;
	returnString += province + nxt;
	returnString += country + nxt;
	returnString += phone + nxt;
	returnString += cuisine + nxt;
	returnString += webaddress + nxt;
	returnString += openHours + nxt;
	returnString += closeHours + nxt;
	returnString += cost + nxt;
	returnString += alcohol + nxt;
	returnString += payment + nxt;
	returnString += description + nxt;
	returnString += reservationsAccepted + nxt;
	returnString += reservationsRecommended + nxt;
	returnString += imagePath;

	return returnString;

    }

}
