/**
 * Restaurantica restaurant recommendation system
 * ECSE 321 - Introduction to Software Engineering
 * Term-Long Project, Misson 4, Due: 03, Dec, 2009
 *==============================================================================
 * Ad entity class - stores an Ad object for use in the system.
 *==============================================================================
 * A simple class, just constructors, getters, and setters. The most important
 * thing to know about this entity class is that it does NOT verify the contents
 * of the ad object. It is up to the caller to ensure that the information
 * stored is all valid!
 *==============================================================================
 * Author: Iain Macdonald - Nov. 2009
 * For questions, or comments e-mail:
 * xiainx@gmail.com
 */

package entities;

public class ad extends entity{

    // Fields in the database
    private int adID;
    private String imagePath;
    private String hyperlink;
    private int timesClicked;

    /**
     * Parameterless constructor
     */
    public ad() {
    }

    /**
     * Parameterized constructor
     * Please pay careful attention to the order of the arguments.
     */
    public ad(int adID, String imagePath, String hyperlink, int timesClicked) {
	this.adID = adID;
	this.imagePath = imagePath;
	this.hyperlink = hyperlink;
	this.timesClicked = timesClicked;
    }

    // Getters and setters, automatically generated by NetBeans
    public int getAdID() {
	return adID;
    }

    public void setAdID(int adID) {
	this.adID = adID;
    }

    public String getHyperlink() {
	return hyperlink;
    }

    public void setHyperlink(String hyperlink) {
	this.hyperlink = hyperlink;
    }

    public String getImagePath() {
	return imagePath;
    }

    public void setImagePath(String imagePath) {
	this.imagePath = imagePath;
    }

    public int getTimesClicked() {
	return timesClicked;
    }

    public void setTimesClicked(int timesClicked) {
	this.timesClicked = timesClicked;
    }

    /**
     * toString
     *
     * Returns the current state of the object as a string.
     */
    public String toString(){
	String returnString = "";
	returnString += adID + ", ";
	returnString += imagePath + ", ";
	returnString += hyperlink + ", ";
	returnString += timesClicked;
	return returnString;
    }

}
